### ISSUE TITLE
Android Compile Crash On GitHub

### ISSUE THREAD

**Issue by jigsaw-4277821** [openfl/lime#1544]
im trying to compile an app and it keeps crashing with this
`/home/runner/haxelib/hxcpp/4,2,1/include/hxcpp.h:23:13: fatal error: 'typeinfo' file not found #include <typeinfo> ^~~~~~~~~~ 1 error generated. Error: Could not create PCH`

**Comment by joshtynjala** [comment]
@jigsaw-4277821 Which version of the Android NDK are you using? NDK r21e usually works well. I think that you get this error when you try to use a newer NDK version than that.

**Comment by jigsaw-4277821** [comment]
Im using ndk r20b

**Comment by jigsaw-4277821** [comment]
@joshtynjala I tryed ndk r21e but nothing changed

**Comment by player-03** [comment]
Copying the workflow file from the other issue:

```yml
# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildAndroid:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.4
          
      - name: Cache haxelib path
        uses: actions/cache@v2
        with:
          path: |
            %~/haxelib%
          key: ${{ runner.os }}-android
          
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.8
        
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: nttld/setup-ndk@v1.0.6
        with:
          ndk-version: r15c

      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install hxcpp > /dev/null
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib install flixel-tools
          haxelib install flixel-ui 
          haxelib install flixel-addons
          haxelib install hscript
          haxelib git linc_luajit https://github.com/jigsaw-4277821/linc_luajit
          haxelib git extension-androidtools https://github.com/jigsaw-4277821/extension-androidtools  
          haxelib git extension-videoview https://github.com/jigsaw-4277821/extension-videoview
          haxelib list
          
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: |
          haxelib run lime setup android
          haxelib run lime build android --app-version="4.0.0-${{ github.run_id}}"
          
      - name: Publish Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/debug
```
