### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mcagabe19** [openfl/lime#1609]
we can change android gradle build `assembleDebug` to `assembleRelease`?
if we can how idk

**Comment by mcagabe19** [comment]
> https://lime.openfl.org/docs/project-files/xml-format/#certificate
> 
> > Use `<certificate />` tags to add a keystore for release signing on certain platforms.
> > If you do not include the password attribute, you will be prompted for your certificate password at the command-line.
> > For Android, the alias will be set to the file name of your certificate by default, without the extension. If the alias name is different, you can use the alias attribute.
> > If you have set the password attribute, the alias_password attribute will default to the same value. Otherwise you can add an alias-password attribute to specify a different value.
> > `<certificate path="to/certificate.crt" password="1234" alias="my-alias" alias-password="4321" />`

i got this error
![Screenshot_2022_1205_211629](https://user-images.githubusercontent.com/82843871/205711851-28fe114e-18d6-4b67-89a3-f42255dbb6ab.jpg)

**Comment by player-03** [comment]
I assume you followed the [instructions to generate a certificate](https://developer.android.com/studio/publish/app-signing)?

**Comment by mcagabe19** [comment]
> I assume you followed the [instructions to generate a certificate](https://developer.android.com/studio/publish/app-signing)?

i not have pc i followed [this](https://linuxhint.com/create-crt-file-linux/)

**Comment by player-03** [comment]
Well that's your problem. Gotta generate an Android-compatible certificate, and that means following the Android documentation. By searching for "generate Android certificate without Studio," it wasn't hard to find [command-line instructions](https://developer.android.com/studio/build/building-cmdline#sign_cmdline).

Also, [making your passphrase public](https://github.com/mcagabe19/FNF-VsSteve-Source-Code-2.5/blob/main/Project.xml#L161) totally defeats the point and might get your app taken down. You gotta use [encrypted secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets) for security. It might look like this, assuming environment variables are in fact passed through:

```yml
- name: Compile
  run: haxelib run lime build android -armv7 -D no-compilation -D luajit_static -D macro-times -D analyzer-optimize -${{ matrix.arch }} --app-version="4.0.0-${{ github.run_id }}"
  env:
    cert_pass: ${{ secrets.cert_pass }}
    cert_alias_pass: ${{ secrets.cert_alias_pass }}
```

```xml
<certificate path="the.crt" password="${cert_pass}" alias="the" alias-password="${cert_alias_pass}" />
```

**Comment by mcagabe19** [comment]
> Well that's your problem. Gotta generate an Android-compatible certificate, and that means following the Android documentation. By searching for "generate Android certificate without Studio," it wasn't hard to find [command-line instructions](https://developer.android.com/studio/build/building-cmdline#sign_cmdline).
> 
> Also, [making your passphrase public](https://github.com/mcagabe19/FNF-VsSteve-Source-Code-2.5/blob/main/Project.xml#L161) totally defeats the point and might get your app taken down. You gotta use [encrypted secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets) for security. It might look like this, assuming environment variables are in fact passed through:
> 
> ```yaml
> - name: Compile
>   run: haxelib run lime build android -armv7 -D no-compilation -D luajit_static -D macro-times -D analyzer-optimize -${{ matrix.arch }} --app-version="4.0.0-${{ github.run_id }}"
>   env:
>     cert_pass: ${{ secrets.cert_pass }}
>     cert_alias_pass: ${{ secrets.cert_alias_pass }}
> ```
> 
> ```
> <certificate path="the.crt" password="${cert_pass}" alias="the" alias-password="${cert_alias_pass}" />
> ```

still not working [check](https://github.com/mcagabe19/FNF-VsSteve-Source-Code-2.5/actions/runs/3623785950/jobs/6110042313#step:10:1808) actions error,and [here](https://github.com/mcagabe19/FNF-VsSteve-Source-Code-2.5/blob/main/Project.xml) my current project.xml ig we cant do this i using termux for do certificate (no proot-distro)

**Comment by player-03** [comment]
You entered the secrets into GitHub, I assume?

I'm guessing Project.xml couldn't read the environment variables, but we can check to be sure:

```yml
- name: Compile
  run: haxelib run lime build android -armv7 -D no-compilation -D luajit_static -D macro-times -D analyzer-optimize -${{ matrix.arch }} --app-version="4.0.0-${{ github.run_id }}"
  env:
    test_value: 12345
```

```xml
<echo value="${test_value}" />
```

Assuming that's the problem, try going back to `assembleDebug` and using [r0adkll/sign-android-release](https://github.com/marketplace/actions/sign-android-release) afterwards.
